[package]
name = "imp"
version = "0.1.0"
edition = "2021"
authors = ["Vladislav Mamon <hello@vm.codes>"]
description = "Simple CLI to help scaffold projects from templates in a touch."
repository = "https://github.com/norskeld/imp"
publish = false

[dependencies]
clap = { version = "3.0", features = ["cargo", "derive"] }
chumsky = { version = "0.8" }
flate2 = { version = "1.0" }
reqwest = { version = "0.11", features = ["json"] }
tar = { version = "0.4" }
tokio = { version = "1.16", features = ["full"] }
url = "2.2"
kdl = "4.2"
petgraph = "0.6"
