[package]
name = "arx"
version = "0.1.0"
edition = "2021"
authors = ["Vladislav Mamon <hello@vm.codes>"]
description = "Simple CLI for scaffolding projects from templates in a touch."
repository = "https://github.com/norskeld/arx"
publish = false

[dependencies]
chumsky = { version = "0.8.0" }
clap = { version = "4.4.11", features = ["cargo", "derive"] }
flate2 = { version = "1.0.28" }
glob-match = { version = "0.2.1" }
itertools = { version = "0.12.0" }
kdl = { version = "4.6.0" }
petgraph = { version = "0.6.4", features = ["stable_graph"] }
reqwest = { version = "0.11.22", features = ["json"] }
run_script = { version = "0.10.1" }
tar = { version = "0.4.40" }
tokio = { version = "1.35.0", features = ["macros", "fs", "rt-multi-thread"] }
walkdir = { version = "2.4.0" }

[profile.release]
lto = "thin"
panic = "abort"
opt-level = "s"
